version: 2.1

jobs:
  focal_gcc9_heyoka_head_38:
    docker:
    - image: cimg/base:current
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_gcc9_heyoka_head_38.sh
    - store_artifacts:
        path: doc/_build/html
  focal_gcc9_heyoka_head_release_38:
    docker:
    - image: cimg/base:current
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_gcc9_heyoka_head_release_38.sh
    - store_artifacts:
        path: doc/_build/html
  ubuntu_arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_ubuntu_arm64.sh

workflows:
  version: 2.1
  all_builds:
    jobs:
    - focal_gcc9_heyoka_head_38
    - focal_gcc9_heyoka_head_release_38
    - ubuntu_arm64
