name: GitHub CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  osx_10_15:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash tools/gha_osx.sh
